{"uuid": "bb316051-a2c4-4b7e-b7a4-ba05ed5170dd", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "37810805-0aaf-434e-a69b-f97c4c795f70", "event": "runner_on_unreachable", "pid": 5468, "created": "2022-04-22T13:12:49.459644", "parent_uuid": "9e73ed77-7fb2-51cd-4a4a-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "583f6ef5-87a1-4a75-a430-4b02be7e065f", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-51cd-4a4a-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-51cd-4a4a-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:12:49.442252", "end": "2022-04-22T13:12:49.459565", "duration": 0.017313, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "bb316051-a2c4-4b7e-b7a4-ba05ed5170dd"}}