{"uuid": "cdfacb44-2ba5-4cc0-9a8b-f27273bf0545", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "f66d43fa-9bfa-42b6-b0d7-3a760d968039", "event": "runner_on_unreachable", "pid": 5266, "created": "2022-04-22T13:10:07.252599", "parent_uuid": "9e73ed77-7fb2-ec5f-1934-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "fde719db-0d0f-4762-81ef-bea21d427456", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-ec5f-1934-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-ec5f-1934-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:10:07.230032", "end": "2022-04-22T13:10:07.252522", "duration": 0.02249, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "cdfacb44-2ba5-4cc0-9a8b-f27273bf0545"}}