{"uuid": "56670110-e0d5-42d5-a3de-bd576984957d", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "fa2ab1c4-8faf-447d-8f0b-ae4d6a258958", "event": "runner_on_unreachable", "pid": 5027, "created": "2022-04-22T13:09:26.081659", "parent_uuid": "9e73ed77-7fb2-41d5-3c7e-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "73f7e213-d064-4e22-aaa9-def4281ad9c2", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-41d5-3c7e-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-41d5-3c7e-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:09:26.053625", "end": "2022-04-22T13:09:26.081623", "duration": 0.027998, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "56670110-e0d5-42d5-a3de-bd576984957d"}}