{"uuid": "64079195-ca1f-4607-b106-e7cfc71755da", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "a1d4e342-78c4-4370-98d8-d2e6332e4158", "event": "runner_on_unreachable", "pid": 4217, "created": "2022-04-22T13:03:56.383765", "parent_uuid": "9e73ed77-7fb2-93a5-2b9a-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "9ca2b755-1f35-46c2-81da-cf07c4bb8743", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-93a5-2b9a-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-93a5-2b9a-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:03:56.363909", "end": "2022-04-22T13:03:56.383689", "duration": 0.01978, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "64079195-ca1f-4607-b106-e7cfc71755da"}}