{"uuid": "4f26357e-37bb-4404-b9e6-2541b65af8aa", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "5f284cf3-9397-4d16-855c-6416f60ebd66", "event": "runner_on_unreachable", "pid": 4824, "created": "2022-04-22T13:06:39.952387", "parent_uuid": "9e73ed77-7fb2-803a-dbbd-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "0f2fd7d6-75a3-45f9-adaa-c3884e014ff1", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-803a-dbbd-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-803a-dbbd-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:06:39.929330", "end": "2022-04-22T13:06:39.952307", "duration": 0.022977, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "4f26357e-37bb-4404-b9e6-2541b65af8aa"}}