{"uuid": "e3a24219-cfce-4310-92a2-76727a115ba5", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "7136a5e0-af0a-42bb-8909-6777ef53df6d", "event": "runner_on_unreachable", "pid": 20177, "created": "2022-04-28T17:19:21.885934", "parent_uuid": "9e73ed77-7fb2-9500-eacd-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "3783e1b1-3f55-4cba-8f3b-5b5406358a86", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-9500-eacd-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-9500-eacd-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-28T17:19:21.868045", "end": "2022-04-28T17:19:21.885838", "duration": 0.017793, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "e3a24219-cfce-4310-92a2-76727a115ba5"}}