{"uuid": "ac50357b-f23f-404f-a459-4eda6ecfd67c", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "5444d2c6-d6e0-40d1-8260-2ab14e401c37", "event": "runner_on_unreachable", "pid": 9446, "created": "2022-04-22T13:46:05.209704", "parent_uuid": "9e73ed77-7fb2-914e-7e2f-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "af51e96a-120e-4949-9fa3-bd4383afdd97", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-914e-7e2f-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-914e-7e2f-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:46:05.156088", "end": "2022-04-22T13:46:05.209606", "duration": 0.053518, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "ac50357b-f23f-404f-a459-4eda6ecfd67c"}}