{"uuid": "50a771f8-f9f6-4e7f-bd29-dba99b7764ca", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "f1913fa0-e45a-42db-b639-63f5b9361a19", "event": "runner_on_unreachable", "pid": 97554, "created": "2022-05-01T08:30:15.689007", "parent_uuid": "9e73ed77-7fb2-f6c2-0781-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "3713ec4a-0aa9-493c-8f38-0e1d82bbfe9e", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-f6c2-0781-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-f6c2-0781-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-05-01T08:30:15.671882", "end": "2022-05-01T08:30:15.688924", "duration": 0.017042, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "50a771f8-f9f6-4e7f-bd29-dba99b7764ca"}}