{"uuid": "776e7817-d517-4f63-ae21-a5584c46c201", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "968ff8c2-9a59-4a8d-9d42-0ed14eb0d2c7", "event": "runner_on_unreachable", "pid": 8757, "created": "2022-04-22T13:43:28.427848", "parent_uuid": "9e73ed77-7fb2-e35d-910a-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "ec75e3fa-d2ca-42e2-b386-af3f7f162e3b", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-e35d-910a-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-e35d-910a-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:43:28.409165", "end": "2022-04-22T13:43:28.427767", "duration": 0.018602, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "776e7817-d517-4f63-ae21-a5584c46c201"}}