{"uuid": "ad689bd3-0914-4e8e-a724-9df99ce7f02f", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "3aeae1d8-e08b-4f69-b588-055b12764642", "event": "runner_on_unreachable", "pid": 5140, "created": "2022-04-22T13:09:34.344667", "parent_uuid": "9e73ed77-7fb2-86d8-9dd1-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "4df45475-2bda-4a4b-b05f-a880b02c52a2", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-86d8-9dd1-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-86d8-9dd1-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:09:34.324747", "end": "2022-04-22T13:09:34.344579", "duration": 0.019832, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "ad689bd3-0914-4e8e-a724-9df99ce7f02f"}}