{"uuid": "eb105302-40c3-43b8-bddf-fdd9400d2731", "counter": 7, "stdout": "\u001b[1;31mfatal: [192.168.1.1]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused\", \"unreachable\": true}\u001b[0m", "start_line": 5, "end_line": 6, "runner_ident": "8080a661-b50d-4d4f-be3d-e165a7a5eb02", "event": "runner_on_unreachable", "pid": 9096, "created": "2022-04-22T13:45:08.232306", "parent_uuid": "9e73ed77-7fb2-fbd9-9fcf-00000000000f", "event_data": {"playbook": "deploy.yaml", "playbook_uuid": "85167eec-0d32-471d-be88-1a9ee2d04642", "play": "this is a  hello world example", "play_uuid": "9e73ed77-7fb2-fbd9-9fcf-000000000007", "play_pattern": "all", "task": "Gathering Facts", "task_uuid": "9e73ed77-7fb2-fbd9-9fcf-00000000000f", "task_action": "gather_facts", "task_args": "", "task_path": "/Users/devops/data/project/python/pgoops/upload/iac/helloworld/project/deploy.yaml:2", "host": "192.168.1.1", "remote_addr": "192.168.1.1", "start": "2022-04-22T13:45:08.215029", "end": "2022-04-22T13:45:08.232215", "duration": 0.017186, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.1.1 port 22: Connection refused", "changed": false}, "uuid": "eb105302-40c3-43b8-bddf-fdd9400d2731"}}